# Generated by Django 2.1 on 2018-08-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='comment',
            new_name='name',
        ),
    ]
